logging:
  level:
    ROOT: DEBUG
    org.springframework.cloud.config: INFO


server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10011
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760
    content-type: "application/vnd.api.v1+json"
    accept-type: "application/vnd.api.v1+json"
    base-url: "http://elastic-query-service/elastic-query-service/documents"
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
  query:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: 'e487635a-74e4-462a-a044-d908a01486bd'
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/microservices_realm
  thymeleaf:
    cache: false

security:
  default-client-id: keycloak
  logout-success-url: http://localhost:8184/elastic-query-web-client

user-config:
  username: user
  password: 123
  role: USER