twitter-to-kafka-service:
  welcome-message: Welcome to the Twitter Kafka Service
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  enable-v2-tweets: false
  enable-v0-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 1000
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}

retry-config:
  initial-interval-ms: 2000
  max-interval-ms: 30000
  multiplier: 2.0
  max-attempts: 50
  sleep-time-ms: 1000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name:
    - twitter-topic
  topics-t-create: 3
  replication-factor: 3

